setup retry if upgrade failed

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -33,11 +33,23 @@ jobs:
         with:
           version: 'v3.8.0'  # Specify the Helm version you need
 
-      - name: Upgrade Helm chart for backend
+      - name: Retry Helm upgrade for backend
         run: |
           SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
-          helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
-            --set backend.image.tag=$SHORT_SHA \
+          RETRIES=5
+          COUNT=0
+          until [ $COUNT -ge $RETRIES ]
+          do
+            helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
+              --set backend.image.tag=$SHORT_SHA && break
+            COUNT=$[$COUNT+1]
+            echo "Retrying... ($COUNT/$RETRIES)"
+            sleep 30
+          done
+          if [ $COUNT -eq $RETRIES ]; then
+            echo "Helm upgrade failed after $RETRIES attempts"
+            exit 1
+          fi
 
   build-frontend:
     runs-on: [self-hosted]  # Use the self-hosted runner
@@ -61,8 +73,20 @@ jobs:
           docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA .
           docker push ${{ secrets.DOCKER_USERNAME }}/frontend-app:$SHORT_SHA
 
-      - name: Upgrade Helm chart for frontend
+      - name: Retry Helm upgrade for frontend
         run: |
           SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-5)
-          helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
-            --set frontend.image.tag=$SHORT_SHA \
+          RETRIES=5
+          COUNT=0
+          until [ $COUNT -ge $RETRIES ]
+          do
+            helm upgrade stock-app /home/sigmoid/Desktop/stock-app/stock-monitoring-system/stock-app \
+              --set frontend.image.tag=$SHORT_SHA && break
+            COUNT=$[$COUNT+1]
+            echo "Retrying... ($COUNT/$RETRIES)"
+            sleep 30
+          done
+          if [ $COUNT -eq $RETRIES ]; then
+            echo "Helm upgrade failed after $RETRIES attempts"
+            exit 1
+          fi
